### ISSUE TITLE
sigma_d_tot is 0 in some cases where it shouldn't

### ISSUE THREAD

**Issue by isilber** [columncolab/EMC2#28]
In the case I examined, the pl fields all have '0' values (no precipitating ice class) but the other fields are filled with other finite values. While sigma_d for each hydrometer type (except for pl) has various values, sigma_d_tot == 0, which is obviously wrong. 
The problem in this case definitely revolves around sigma_d_numer_tot, which is consistently == 0, although it definitely shouldn't.

**Comment by rcjackson** [comment]
I suspect this is due to an underflow error in the calc_sigma_d subroutine caused by an improper conversion from float64 to float32. I've located the problematic line (in sigma_d_tot_numer) and fixed it. Please let me know if this looks reasonable...it does to me. I suspect the very high spectral width near the ground is due to the large size of drops at that point, but when you average in the other species the spectral width follows a very linear pattern with height.
![new_subcol_figure](https://user-images.githubusercontent.com/22085748/94460429-56e09d00-017e-11eb-854f-8a62034a79ca.png)
